server:  
  port: ${PORT:2222}

spring:  
  application:
    name: account-service
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  zipkin:
    base-url: http://localhost:9411

eureka:  
  client:
    serviceUrl:
      defaultZone:  ${DISCOVERY_URL:http://eureka-server:8761}/eureka/
  instance:
    preferIpAddress: true
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
      
ribbon:
  eureka:
    enabled: true